module ccid

// Generated by 7ka-Hiira/ccid-tools
const tests = [
	// Min
	['0000000000000000000000000000000000000000000000000000000000000001',
		'con1w508d6qejxtdg4y5r3zarvary0c5xw7ktdsum3'],
	// Max
	['fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140',
		'con14h0ycu78h88wzldxc7e79vhw5xsde0n84uvr0s']
	// Random values
	['a7285227e7537867996310e1f57ce332ae0fd9d1154c72b63c49b1db16528604',
		'con1px4s9pju9s33a2a7nwu0z7epdrwhzjxndh2aug'],
	['c560fa3cb18ee761f5f7b73b8a757a393cfad364a81b42ceda7a679cb05ddc9f',
		'con183789zapune4udqzcjgyz5l620ppr922yyjw02'],
	['04d806b8c3b964f2ad186445a682bf411b51277bddbbbff59db04368126f1965',
		'con173stnde77c7t4dz04pfel2lgcqeyjjfywnx9ce'],
	['00d283c993c9f778e53a159825322d1f79ee908a3a4de4bd339ac5b1b1cabe18',
		'con1sn2qjt6l3l0evdad7p57u7plrcdx7c6u3ngl37'],
]

fn test_api() {
	for test in tests {
		privkey := test[0]
		pubkey := privkey_to_pubkey(privkey)!
		ccid := pubkey_to_ccid(pubkey)!
		assert ccid == test[1]
	}
}
